---
- name: Check syncthing_version variable
  assert:
    that: syncthing_version in ["0.12.10"]

- name: Import syncthing GPG key to apt
  apt_key:
    url: 'https://syncthing.net/release-key.txt'
    state: present

- name: Add syncthing repository
  apt_repository:
    repo: 'deb http://apt.syncthing.net/ syncthing release'
    state: present

- name: Add syncthing repository preferences
  template:
    src: apt_syncthing.pref.2
    dest: /etc/apt/preferences.d/syncthing.pref

- name: Install syncthing
  apt:
    pkg: syncthing={{ syncthing_version }}
    state: installed

- name: Install ufw syncthing rules
  copy:
    src: ufw-syncthing
    dest: /etc/ufw/applications.d/ufw-syncthing
    owner: root
    mode: 0644
  when: syncthing_use_ufw

- name: Allow syncthing ufw
  ufw: rule=allow name=syncthing
  when: syncthing_use_ufw
